// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "ExecuteWebScrapingTask",
                "parameters": [
                    {
                        "description": "url to analyze",
                        "name": "url",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/interfaces.TargetURL"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/interfaces.PageData"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "interfaces.PageData": {
            "type": "object",
            "properties": {
                "accessible_urls": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "boolean"
                    }
                },
                "external_links": {
                    "type": "integer"
                },
                "headings": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "html_version": {
                    "type": "string"
                },
                "inaccessible_links": {
                    "type": "integer"
                },
                "internal_links": {
                    "type": "integer"
                },
                "login_form": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "interfaces.TargetURL": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1/analyzer",
	Schemes:          []string{},
	Title:            "Web Analyzer API",
	Description:      "An API to analyze a web page and it's contents",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
